import type { Metadata } from "next";
import { InteriorHero, TextBlockGrid } from "@/components/interior-page";
import { PdfActions } from "@/components/public-data";
import { Section, SectionHeading } from "@/components/section";
import { pageIntros } from "@/lib/site-data";

export const metadata: Metadata = { title: "How to Apply", description: "Reporting steps and documents for O-Level and A-Level admission to Rubaare Secondary School.", alternates: { canonical: "/admissions/how-to-apply" } };

export default function HowToApplyPage() {
  return <><InteriorHero intro={{ ...pageIntros.admissions, eyebrow: "How to Apply", title: "Prepare for admission and reporting.", description: "Follow the official admission letter for your level and bring the required documents when reporting." }} breadcrumbs={[{ label: "Admissions", href: "/admissions" }, { label: "How to Apply", href: "/admissions/how-to-apply" }]} /><TextBlockGrid eyebrow="Reporting" title="Admission preparation." description="The supplied letters do not define an online application, selection criteria or general application deadline." blocks={[{ title: "1. Choose the correct level", body: "Use the O-Level pack for lower-secondary entry or the A-Level pack for advanced-secondary entry." }, { title: "2. Prepare former-school documents", body: "O-Level entrants bring a recommendation and result slip. A-Level entrants bring their pass slip or original and photocopy, a recommendation from the former school, and an identity card." }, { title: "3. Review and sign the rules", body: "The parent or guardian and student should read and sign the school rules and return them on reporting day." }, { title: "4. Report to school", body: "Reporting hours are 08:00am–5:00pm. The letters state that failure to report within the first week may cause the vacancy to be given to someone on the waiting list." }]} /><Section className="bg-white"><SectionHeading eyebrow="Official Letters" title="Download admission documents." description="Use the complete packs for all forms, fees and requirements." /><div className="grid gap-6 md:grid-cols-2"><div><h2 className="font-serif text-xl font-semibold text-[var(--school-blue-dark)]">O-Level Admission Pack</h2><PdfActions href="/downloads/o-level-admission-pack-2026.pdf" title="O-Level Admission Pack 2026" /></div><div><h2 className="font-serif text-xl font-semibold text-[var(--school-blue-dark)]">A-Level Admission Pack</h2><PdfActions href="/downloads/a-level-admission-pack-2026.pdf" title="A-Level Admission Pack 2026" /></div></div></Section></>;
}
