import type { Metadata } from "next";
import { InteriorHero } from "@/components/interior-page";
import { PdfActions } from "@/components/public-data";
import { Section, SectionHeading } from "@/components/section";
import { pageIntros } from "@/lib/site-data";

export const metadata: Metadata = { title: "Admission Requirements", description: "Verified O-Level and A-Level reporting, uniform and boarding requirements for Rubaare Secondary School.", alternates: { canonical: "/admissions/requirements" } };
const List = ({ title, items }: { title: string; items: ReadonlyArray<string> }) => <article className="bg-white p-6"><h2 className="font-serif text-2xl font-semibold text-[var(--school-blue-dark)]">{title}</h2><ul className="mt-4 grid gap-2 text-sm leading-6 text-[var(--school-muted)]">{items.map((item) => <li key={item} className="border-t border-[var(--school-border)] pt-2">{item}</li>)}</ul></article>;

export default function RequirementsPage() {
  return <><InteriorHero intro={{ ...pageIntros.admissions, eyebrow: "Requirements", title: "Admission and reporting requirements.", description: "Review the verified summary below and use the official PDF documents for the complete operational wording." }} breadcrumbs={[{ label: "Admissions", href: "/admissions" }, { label: "Requirements", href: "/admissions/requirements" }]} />
    <Section className="bg-[var(--school-cream)]"><SectionHeading eyebrow="O-Level" title="O-Level requirements." description="Documents, personal items, uniform and boarding preparation from the 2026 O-Level admission pack." /><div className="mt-8 grid gap-5 lg:grid-cols-3"><List title="Documents & Class Items" items={["Recommendation and result slip", "Mathematical set and dictionary", "Pens, pencils and at least 16 exercise books", "One ream of ROTATRIM paper", "English Bible and folder file", "Required passport photographs"]} /><List title="Uniform" items={["Girls: white short-sleeve blouse, denim blue skirt from school, sweater, black closed shoes and white socks", "Boys: white short-sleeve shirt, denim blue shorts from school, sweater, black closed shoes and white socks", "Jungle shoes are not allowed", "Sportswear is bought from school; each student brings sports shoes"]} /><List title="Boarding & Personal Items" items={["Mattress, blanket, bed sheets, bucket and 10-litre jerrycan", "Slippers, plate, cup, peeling knife and torch", "Pocket money and personal effects", "Girls: three red T-shirts and three black skirts", "Boys: three yellow T-shirts and three black trousers or shorts", "The letter states that boys' boarding vacancies are few and interested families should notify the office"]} /></div><PdfActions href="/downloads/o-level-admission-pack-2026.pdf" title="O-Level Admission Pack 2026" /></Section>
    <Section className="bg-white"><SectionHeading eyebrow="A-Level" title="A-Level requirements." description="Documents, uniform and boarding preparation from the 2026 A-Level admission pack." /><div className="mt-8 grid gap-5 lg:grid-cols-3"><List title="Documents & Study" items={["Pass slip or original and photocopy", "Recommendation from former school", "Identity card", "Three principal subjects", "Computer Studies or Sub-Mathematics as subsidiary", "General Paper is compulsory", "Bible and one ream of ROTATRIM paper"]} /><List title="Uniform" items={["Boys: brown trouser and sweater, white long-sleeve shirt, white socks and black closed leather shoes", "Girls: brown skirt and sweater, white long-sleeve blouse, white socks and black closed short-heel shoes", "Trouser or skirt is bought at school", "Jungle and tennis shoes are not accepted"]} /><List title="Boarding & Personal Items" items={["Mattress, bedding, basin, 10-litre jerrycan and slippers", "Plate, cup, torch and personal effects", "Girls: three black skirts and three blue T-shirts or blouses", "Boys: three blue T-shirts or shirts and three black trousers", "See the boarding requirements PDF for the complete list"]} /></div><PdfActions href="/downloads/a-level-admission-pack-2026.pdf" title="A-Level Admission Pack 2026" /></Section>
    <Section className="bg-[var(--school-cream)]"><SectionHeading eyebrow="Boarding" title="Complete hostel requirements." description="Download the official boarding and hostel requirements for the full class, uniform and dormitory list." /><PdfActions href="/downloads/boarding-hostel-requirements-2026.pdf" title="Boarding/Hostel Requirements 2026" /></Section>
  </>;
}
