import type { Metadata } from "next";
import { InteriorHero, TextBlockGrid } from "@/components/interior-page";
import { pageIntros } from "@/lib/site-data";

export const metadata: Metadata = { title: "School Facilities", description: "Verified utilities, completed projects and current campus development at Rubaare Secondary School.", alternates: { canonical: "/about/facilities" } };

export default function FacilitiesPage() {
  return <><InteriorHero intro={{ ...pageIntros.about, eyebrow: "Facilities", title: "A supported learning environment.", description: "Official school material records essential utilities, learning spaces, completed projects and current campus development." }} breadcrumbs={[{ label: "About", href: "/about" }, { label: "Facilities", href: "/about/facilities" }]} /><TextBlockGrid eyebrow="Campus Facilities" title="Learning and daily life at school." description="The following facilities and project states are supported by official school documents and photography." blocks={[{ title: "Electricity", body: "The school is connected to electricity." }, { title: "Standby Generator", body: "A standby generator supports the school's power provision." }, { title: "Solar Power", body: "Solar power is available at the school." }, { title: "Clean Water Project — Complete", body: "The school water project is complete." }, { title: "Computer Laboratory", body: "Official school photography records a computer laboratory used by learners." }, { title: "Boarding Infrastructure", body: "Official structure records identify boys' and girls' dormitory buildings and dormitory-area sanitation facilities." }, { title: "Junior Staff Quarters I — Complete", body: "Junior Staff Quarters I are complete. The school structure record also includes headteacher accommodation." }, { title: "Girls' Dormitory — Under Construction", body: "Construction of a three-storeyed girls' dormitory was launched by Rt. Rev. Bishop Nathan Ahimbisibwe on 11 August 2026 to improve accommodation for girls. The school has requested support for the project." }]} /></>;
}
