export type SchoolMediaCategory =
  | "brand"
  | "leadership"
  | "campus"
  | "academics"
  | "students"
  | "sports"
  | "events"
  | "water-project"
  | "master-plan"
  | "gallery"
  | "documents";

export type VerificationStatus = "verified" | "school-confirmation-required";

export type SchoolMediaAsset = {
  id: string;
  category: SchoolMediaCategory;
  src: string;
  alt: string;
  width: number;
  height: number;
  credit: string;
  verificationStatus: VerificationStatus;
  source: "official-school-content";
};

export type MasterPlanItem = SchoolMediaAsset & {
  title: string;
  caption: string;
};

export type GalleryAlbum = {
  title: string;
  slug: string;
  description: string;
  coverImage: SchoolMediaAsset;
  images: ReadonlyArray<SchoolMediaAsset>;
};

const officialCredit = "Official Rubaare Secondary School content";

export const schoolMedia = {
  badge: {
    id: "rubaare-school-badge",
    category: "brand",
    src: "/images/school/brand/rubaare-school-badge.jpg",
    alt: "Rubaare Secondary School badge.",
    width: 640,
    height: 960,
    credit: officialCredit,
    verificationStatus: "verified",
    source: "official-school-content",
  },
  headteacher: {
    id: "headteacher-ms-mpeirwe-monic-atukunda",
    category: "leadership",
    src: "/images/school/leadership/headteacher-ms-mpeirwe-monic-atukunda.webp",
    alt: "Headteacher Ms. Mpeirwe Monic Atukunda seated at her desk.",
    width: 1400,
    height: 817,
    credit: officialCredit,
    verificationStatus: "verified",
    source: "official-school-content",
  },
  studentAssembly: {
    id: "student-assembly",
    category: "students",
    src: "/images/school/students/student-assembly.webp",
    alt: "Rubaare Secondary School students seated outdoors during a school gathering.",
    width: 1800,
    height: 1192,
    credit: officialCredit,
    verificationStatus: "verified",
    source: "official-school-content",
  },
  outdoorStudentGathering: {
    id: "outdoor-student-gathering",
    category: "gallery",
    src: "/images/school/gallery/outdoor-student-gathering.webp",
    alt: "Students seated outdoors during a Rubaare Secondary School gathering.",
    width: 1800,
    height: 1192,
    credit: officialCredit,
    verificationStatus: "verified",
    source: "official-school-content",
  },
  classroomLearning: {
    id: "classroom-learning",
    category: "academics",
    src: "/images/school/academics/classroom-learning.webp",
    alt: "Rubaare Secondary School students in a classroom lesson.",
    width: 1600,
    height: 1060,
    credit: officialCredit,
    verificationStatus: "verified",
    source: "official-school-content",
  },
  classroomAssembly: {
    id: "classroom-assembly",
    category: "academics",
    src: "/images/school/academics/classroom-assembly.webp",
    alt: "Students gathered inside a classroom at Rubaare Secondary School.",
    width: 1600,
    height: 1060,
    credit: officialCredit,
    verificationStatus: "verified",
    source: "official-school-content",
  },
  schoolCompound: {
    id: "school-compound",
    category: "campus",
    src: "/images/school/campus/school-compound.webp",
    alt: "A landscaped compound at Rubaare Secondary School.",
    width: 1600,
    height: 1067,
    credit: officialCredit,
    verificationStatus: "verified",
    source: "official-school-content",
  },
  mainSchoolBuilding: {
    id: "main-school-building",
    category: "campus",
    src: "/images/school/campus/main-school-building.webp",
    alt: "A school building and compound at Rubaare Secondary School.",
    width: 1600,
    height: 1060,
    credit: officialCredit,
    verificationStatus: "verified",
    source: "official-school-content",
  },
  schoolBuildingAndWaterPoint: {
    id: "school-building-and-water-point",
    category: "campus",
    src: "/images/school/campus/school-building-and-water-point.webp",
    alt: "A Rubaare Secondary School building near a water point.",
    width: 1600,
    height: 1060,
    credit: officialCredit,
    verificationStatus: "verified",
    source: "official-school-content",
  },
  sportsDayField: {
    id: "sports-day-field",
    category: "sports",
    src: "/images/school/sports/sports-day-field.webp",
    alt: "Students participating in sports day activities on the school field.",
    width: 1600,
    height: 1060,
    credit: officialCredit,
    verificationStatus: "verified",
    source: "official-school-content",
  },
  sportsDayVolleyball: {
    id: "sports-day-volleyball",
    category: "sports",
    src: "/images/school/sports/sports-day-volleyball.webp",
    alt: "Students playing volleyball during sports day.",
    width: 1600,
    height: 1060,
    credit: officialCredit,
    verificationStatus: "verified",
    source: "official-school-content",
  },
  sportsDayRunning: {
    id: "sports-day-running",
    category: "sports",
    src: "/images/school/sports/sports-day-running.webp",
    alt: "Students running during Rubaare Secondary School sports day.",
    width: 1600,
    height: 1060,
    credit: officialCredit,
    verificationStatus: "verified",
    source: "official-school-content",
  },
  waterProjectSiteVisit: {
    id: "water-project-site-visit",
    category: "water-project",
    src: "/images/school/water-project/water-project-site-visit.webp",
    alt: "Water project site visit at Rubaare Secondary School.",
    width: 1500,
    height: 1000,
    credit: officialCredit,
    verificationStatus: "verified",
    source: "official-school-content",
  },
  waterProjectGroupPhoto: {
    id: "water-project-group-photo",
    category: "water-project",
    src: "/images/school/water-project/water-project-group-photo.webp",
    alt: "Group photograph at the Rubaare Secondary School water project site.",
    width: 1500,
    height: 1000,
    credit: officialCredit,
    verificationStatus: "verified",
    source: "official-school-content",
  },
  waterProjectTechnicalDiscussion: {
    id: "water-project-technical-discussion",
    category: "water-project",
    src: "/images/school/water-project/water-project-technical-discussion.webp",
    alt: "Water project technical discussion at Rubaare Secondary School.",
    width: 1500,
    height: 1000,
    credit: officialCredit,
    verificationStatus: "verified",
    source: "official-school-content",
  },
  studentsCollectingWater: {
    id: "students-collecting-water",
    category: "water-project",
    src: "/images/school/water-project/students-collecting-water.webp",
    alt: "Students collecting water at Rubaare Secondary School.",
    width: 1500,
    height: 1000,
    credit: officialCredit,
    verificationStatus: "verified",
    source: "official-school-content",
  },
  christmasCarolsAssembly: {
    id: "christmas-carols-assembly",
    category: "events",
    src: "/images/school/events/christmas-carols-assembly.webp",
    alt: "Students gathered for Christmas carols at Rubaare Secondary School.",
    width: 1600,
    height: 1060,
    credit: officialCredit,
    verificationStatus: "verified",
    source: "official-school-content",
  },
  christmasCarolsPerformance: {
    id: "christmas-carols-performance",
    category: "events",
    src: "/images/school/events/christmas-carols-performance.webp",
    alt: "Students performing during Christmas carols at Rubaare Secondary School.",
    width: 1600,
    height: 1060,
    credit: officialCredit,
    verificationStatus: "verified",
    source: "official-school-content",
  },
  schoolEventGuests: {
    id: "school-event-guests",
    category: "events",
    src: "/images/school/events/school-event-guests.webp",
    alt: "Guests and students during a school event at Rubaare Secondary School.",
    width: 1600,
    height: 1060,
    credit: officialCredit,
    verificationStatus: "school-confirmation-required",
    source: "official-school-content",
  },
} satisfies Record<string, SchoolMediaAsset>;

export const masterPlanItems: ReadonlyArray<MasterPlanItem> = [
  {
    id: "master-plan-gate",
    category: "master-plan",
    src: "/images/school/master-plan/master-plan-gate.webp",
    alt: "Master plan render labelled Gate.",
    width: 1800,
    height: 1200,
    credit: officialCredit,
    verificationStatus: "verified",
    source: "official-school-content",
    title: "Gate",
    caption: "Gate.",
  },
  {
    id: "master-plan-admin-block",
    category: "master-plan",
    src: "/images/school/master-plan/master-plan-admin-block.webp",
    alt: "Master plan render labelled Admin Block.",
    width: 1600,
    height: 1200,
    credit: officialCredit,
    verificationStatus: "verified",
    source: "official-school-content",
    title: "Admin Block",
    caption: "Admin Block.",
  },
  {
    id: "master-plan-overview-building",
    category: "master-plan",
    src: "/images/school/master-plan/master-plan-overview-building.webp",
    alt: "Master plan building render.",
    width: 1600,
    height: 1200,
    credit: officialCredit,
    verificationStatus: "school-confirmation-required",
    source: "official-school-content",
    title: "Proposed Building Render",
    caption: "Proposed building render.",
  },
  {
    id: "master-plan-head-teacher-house",
    category: "master-plan",
    src: "/images/school/master-plan/master-plan-head-teacher-house.webp",
    alt: "Master plan render labelled Head Teacher House.",
    width: 1600,
    height: 1200,
    credit: officialCredit,
    verificationStatus: "verified",
    source: "official-school-content",
    title: "Head Teacher House",
    caption: "Head Teacher House.",
  },
  {
    id: "master-plan-deputy-head-teacher-house",
    category: "master-plan",
    src: "/images/school/master-plan/master-plan-deputy-head-teacher-house.webp",
    alt: "Master plan render labelled D slash Head Teacher House.",
    width: 1600,
    height: 1200,
    credit: officialCredit,
    verificationStatus: "verified",
    source: "official-school-content",
    title: "D/ Head Teacher House",
    caption: "D/ Head Teacher House.",
  },
  {
    id: "master-plan-girls-dormitory",
    category: "master-plan",
    src: "/images/school/master-plan/master-plan-girls-dormitory.webp",
    alt: "Master plan render labelled Girls Dormitory.",
    width: 1600,
    height: 1200,
    credit: officialCredit,
    verificationStatus: "verified",
    source: "official-school-content",
    title: "Girls Dormitory",
    caption: "Girls Dormitory.",
  },
  {
    id: "master-plan-dining-kitchen",
    category: "master-plan",
    src: "/images/school/master-plan/master-plan-dining-kitchen.webp",
    alt: "Master plan render labelled Dining Kitchen.",
    width: 1600,
    height: 1200,
    credit: officialCredit,
    verificationStatus: "verified",
    source: "official-school-content",
    title: "Dining/Kitchen",
    caption: "Dining/Kitchen.",
  },
  {
    id: "master-plan-render-collage",
    category: "master-plan",
    src: "/images/school/master-plan/master-plan-render-collage.webp",
    alt: "Master plan render collage.",
    width: 1800,
    height: 1200,
    credit: officialCredit,
    verificationStatus: "school-confirmation-required",
    source: "official-school-content",
    title: "Render Collage",
    caption: "Proposed development render collage.",
  },
  {
    id: "master-plan-classroom-block-render",
    category: "master-plan",
    src: "/images/school/master-plan/master-plan-classroom-block-render.webp",
    alt: "Master plan classroom block render.",
    width: 1600,
    height: 1200,
    credit: officialCredit,
    verificationStatus: "school-confirmation-required",
    source: "official-school-content",
    title: "Classroom Block Render",
    caption: "Proposed classroom block render.",
  },
  {
    id: "master-plan-additional-building-render",
    category: "master-plan",
    src: "/images/school/master-plan/master-plan-additional-building-render.webp",
    alt: "Additional master plan building render.",
    width: 1600,
    height: 1200,
    credit: officialCredit,
    verificationStatus: "school-confirmation-required",
    source: "official-school-content",
    title: "Additional Building Render",
    caption: "Proposed building render.",
  },
  {
    id: "master-plan-classroom-block-render-02",
    category: "master-plan",
    src: "/images/school/master-plan/master-plan-classroom-block-render-02.webp",
    alt: "Second master plan classroom block render.",
    width: 1600,
    height: 1200,
    credit: officialCredit,
    verificationStatus: "school-confirmation-required",
    source: "official-school-content",
    title: "Classroom Block Render",
    caption: "Proposed classroom block render.",
  },
];

export const galleryAlbums: ReadonlyArray<GalleryAlbum> = [
  {
    title: "Campus",
    slug: "campus",
    description: "School compound and building photography from the official content library.",
    coverImage: schoolMedia.schoolCompound,
    images: [schoolMedia.schoolCompound, schoolMedia.mainSchoolBuilding, schoolMedia.schoolBuildingAndWaterPoint],
  },
  {
    title: "Academics",
    slug: "academics",
    description: "Classroom and learning activity photographs supplied by the school.",
    coverImage: schoolMedia.classroomLearning,
    images: [schoolMedia.classroomLearning, schoolMedia.classroomAssembly],
  },
  {
    title: "Sports Day",
    slug: "sports-day",
    description: "Sports day activity photographs from the official content library.",
    coverImage: schoolMedia.sportsDayVolleyball,
    images: [schoolMedia.sportsDayField, schoolMedia.sportsDayVolleyball, schoolMedia.sportsDayRunning],
  },
  {
    title: "Student Life",
    slug: "student-life",
    description: "Student gathering photographs supplied by the school.",
    coverImage: schoolMedia.studentAssembly,
    images: [schoolMedia.studentAssembly, schoolMedia.outdoorStudentGathering],
  },
  {
    title: "Water Project",
    slug: "water-project",
    description: "Water-project photography from the official content library.",
    coverImage: schoolMedia.waterProjectGroupPhoto,
    images: [
      schoolMedia.waterProjectSiteVisit,
      schoolMedia.waterProjectGroupPhoto,
      schoolMedia.waterProjectTechnicalDiscussion,
      schoolMedia.studentsCollectingWater,
    ],
  },
  {
    title: "Master Plan",
    slug: "master-plan",
    description: "Proposed future development renders supplied in the master-plan folder.",
    coverImage: masterPlanItems[0],
    images: masterPlanItems,
  },
];
